server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: machine-camunda-server
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 4096MB
  cloud:
    nacos:
      config:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        file-extension: yaml
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
      discovery:
        server-addr: ${machine.nacos.server-addr}
        username: ${machine.nacos.username}
        password: ${machine.nacos.password}
        namespace: MACHINE_${spring.profiles.active}
        group: MACHINE_GROUP
  config:
    import:
      - nacos:machine.yaml?refreshEnabled=true
      - nacos:${spring.application.name}.yaml?refreshEnabled=true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${machine.datasource.host}:5432/machine_camunda?tcpKeepAlive=true
    username: ${machine.datasource.username}
    password: ${machine.datasource.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最小空闲连接数
      minimum-idle: 2
      # 最大连接数
      maximum-pool-size: 8

camunda:
  bpm:
    admin-user:
      id: root
      password: root
